output:
  path: 'data/output'
  merged_filename: 'merged'
datamodule_params:
  sentinel_products: 'train'
  mask_path: null
strides:
  - 112
  - 100
ensemble:
  - version_path: data/logs/lightning_logs/version_132
    checkpoint: checkpoints/epoch=15-step=6400.ckpt
  - version_path: data/logs/lightning_logs/version_133
    checkpoint: checkpoints/epoch=3-step=1600.ckpt
  - version_path: data/logs/lightning_logs/version_134
    checkpoint: checkpoints/epoch=8-step=3600.ckpt
  - version_path: data/logs/lightning_logs/version_135
    checkpoint: checkpoints/epoch=21-step=8800.ckpt
  - version_path: data/logs/lightning_logs/version_136
    checkpoint: checkpoints/epoch=9-step=4000.ckpt
