output:
  path: 'data/output'
  merged_filename: 'unet-neuland-34'
datamodule_params:
  sentinel_products: 'neuland'
  mask_path: null
strides:
  - 172
  - 180
ensemble:
  # unet
  # - version_path: data/logs/lightning_logs/version_132
  #   checkpoint: checkpoints/epoch=15-step=6400.ckpt
  # - version_path: data/logs/lightning_logs/version_133
  #   checkpoint: checkpoints/epoch=3-step=1600.ckpt
  # - version_path: data/logs/lightning_logs/version_134
  #   checkpoint: checkpoints/epoch=8-step=3600.ckpt
  # - version_path: data/logs/lightning_logs/version_135
  #   checkpoint: checkpoints/epoch=21-step=8800.ckpt
  # - version_path: data/logs/lightning_logs/version_136
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt

  # farseg
  # - version_path: data/logs/lightning_logs/version_137
  #   checkpoint: checkpoints/epoch=3-step=1600.ckpt
  # - version_path: data/logs/lightning_logs/version_138
  #   checkpoint: checkpoints/epoch=0-step=400.ckpt
  # - version_path: data/logs/lightning_logs/version_139
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt

  # unet with larger training image set
  # - version_path: data/logs/lightning_logs/version_140
  #   checkpoint: checkpoints/epoch=13-step=5600.ckpt
  # - version_path: data/logs/lightning_logs/version_141
  #   checkpoint: checkpoints/epoch=14-step=6000.ckpt
  # - version_path: data/logs/lightning_logs/version_142
  #   checkpoint: checkpoints/epoch=8-step=3600.ckpt

  # fcn - literally useless
  # - version_path: data/logs/lightning_logs/version_145
  #   checkpoint: checkpoints/epoch=1-step=800.ckpt

  # For thesis FCN section
  # - version_path: data/logs/lightning_logs/version_148
  #   checkpoint: checkpoints/epoch=1-step=800.ckpt
  # - version_path: data/logs/lightning_logs/version_149
  #   checkpoint: checkpoints/epoch=2-step=1200.ckpt
  # - version_path: data/logs/lightning_logs/version_150
  #   checkpoint: checkpoints/epoch=8-step=3600.ckpt
  # - version_path: data/logs/lightning_logs/version_151
  #   checkpoint: checkpoints/epoch=4-step=2000.ckpt
  # - version_path: data/logs/lightning_logs/version_152
  #   checkpoint: checkpoints/epoch=4-step=2000.ckpt

  # For thesis FarSeg section
  # resnet18
  # - version_path: data/logs/lightning_logs/version_153
  #   checkpoint: checkpoints/epoch=1-step=800.ckpt
  # - version_path: data/logs/lightning_logs/version_154
  #   checkpoint: checkpoints/epoch=3-step=1600.ckpt
  # resnet34
  # - version_path: data/logs/lightning_logs/version_163
  #   checkpoint: checkpoints/epoch=11-step=4800.ckpt
  # - version_path: data/logs/lightning_logs/version_164
  #   checkpoint: checkpoints/epoch=7-step=3200.ckpt
  # resnet50
  # - version_path: data/logs/lightning_logs/version_155
  #   checkpoint: checkpoints/epoch=19-step=8000.ckpt
  # - version_path: data/logs/lightning_logs/version_156
  #   checkpoint: checkpoints/epoch=2-step=1200.ckpt
  # - version_path: data/logs/lightning_logs/version_157
  #   checkpoint: checkpoints/epoch=27-step=11200.ckpt
  # - version_path: data/logs/lightning_logs/version_158
  #   checkpoint: checkpoints/epoch=4-step=2000.ckpt
  # resnet101
  # - version_path: data/logs/lightning_logs/version_165
  #   checkpoint: checkpoints/epoch=12-step=5200.ckpt
  # - version_path: data/logs/lightning_logs/version_166
  #   checkpoint: checkpoints/epoch=10-step=4400.ckpt
  # - version_path: data/logs/lightning_logs/version_167
  #   checkpoint: checkpoints/epoch=8-step=3600.ckpt
  # - version_path: data/logs/lightning_logs/version_168
  #   checkpoint: checkpoints/epoch=5-step=2400.ckpt

  # For thesis U-Net section
  # # 64-512
  # - version_path: data/logs/lightning_logs/version_159
  #   checkpoint: checkpoints/epoch=10-step=4400.ckpt
  # - version_path: data/logs/lightning_logs/version_160
  #   checkpoint: checkpoints/epoch=10-step=4400.ckpt
  # # 32-512
  # - version_path: data/logs/lightning_logs/version_161
  #   checkpoint: checkpoints/epoch=14-step=6000.ckpt
  # - version_path: data/logs/lightning_logs/version_162
  #   checkpoint: checkpoints/epoch=3-step=1600.ckpt
  # # 64-1024
  # - version_path: data/logs/lightning_logs/version_169
  #   checkpoint: checkpoints/epoch=10-step=4400.ckpt
  # - version_path: data/logs/lightning_logs/version_170
  #   checkpoint: checkpoints/epoch=10-step=4400.ckpt

  # unet with KRA training data
  # - version_path: data/logs/lightning_logs/version_171
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt
  # - version_path: data/logs/lightning_logs/version_172
  #   checkpoint: checkpoints/epoch=7-step=3200.ckpt

  # # unet with KQV training data
  # # 64-512
  # - version_path: data/logs/lightning_logs/version_173
  #   checkpoint: checkpoints/epoch=1-step=800.ckpt
  # - version_path: data/logs/lightning_logs/version_176
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt
  # # 32-512
  # - version_path: data/logs/lightning_logs/version_174
  #   checkpoint: checkpoints/epoch=14-step=6000.ckpt
  # - version_path: data/logs/lightning_logs/version_177
  #   checkpoint: checkpoints/epoch=7-step=3200.ckpt
  # # 64-1024
  # - version_path: data/logs/lightning_logs/version_178
  #   checkpoint: checkpoints/epoch=4-step=2000.ckpt
  # - version_path: data/logs/lightning_logs/version_179
  #   checkpoint: checkpoints/epoch=15-step=6400.ckpt

  # - version_path: data/logs/lightning_logs/version_189
  #   checkpoint: checkpoints/epoch=6-step=2800.ckpt

  # with smaller features
  # - version_path: data/logs/lightning_logs/version_191
  #   checkpoint: checkpoints/epoch=12-step=5200.ckpt

  # with smaller features and larger weight_decay (pretty good)
  # - version_path: data/logs/lightning_logs/version_192
  #   checkpoint: checkpoints/epoch=17-step=7200.ckpt
  # with smaller features and smaller lr (pretty bad, but learning was less erratic)
  # - version_path: data/logs/lightning_logs/version_193
  #   checkpoint: checkpoints/epoch=31-step=12800.ckpt

  # with smaller features and lr of 5e-5
  #   weight_decay: 0.0001 (useless)
  # - version_path: data/logs/lightning_logs/version_194
  #   checkpoint: checkpoints/epoch=12-step=5200.ckpt
  #   weight_decay: 0.001 (highlights a lot of ground, but doesn't look too bad)
  # - version_path: data/logs/lightning_logs/version_195
  #   checkpoint: checkpoints/epoch=23-step=9600.ckpt

  # with dry training data and same as last settings
  # - version_path: data/logs/lightning_logs/version_196
  #   checkpoint: checkpoints/epoch=13-step=5600.ckpt
  # - version_path: data/logs/lightning_logs/version_197
  #   checkpoint: checkpoints/epoch=18-step=7600.ckpt

  # with dry training including Neuland
  # - version_path: data/logs/lightning_logs/version_198
  #   checkpoint: checkpoints/epoch=15-step=6400.ckpt
  # - version_path: data/logs/lightning_logs/version_199
  #   checkpoint: checkpoints/epoch=15-step=6400.ckpt
  # - version_path: data/logs/lightning_logs/version_200
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt
  # - version_path: data/logs/lightning_logs/version_201
  #   checkpoint: checkpoints/epoch=6-step=2800.ckpt

  # with neuland 2015/16 and september and june 2025 from the rest
  # - version_path: data/logs/lightning_logs/version_203
  #   checkpoint: checkpoints/epoch=24-step=10000.ckpt

  # with only train, no neuland. Good-ish results in mariscal, less so in neuland. Decently good in argentina
  # - version_path: data/logs/lightning_logs/version_211
  #   checkpoint: checkpoints/epoch=9-step=4000.ckpt

  # with only loma plata, filadelfia and neuland, only get pitch black

  # With all kna, knb, kpc train data
  # - version_path: data/logs/lightning_logs/version_214
  #   checkpoint: checkpoints/epoch=11-step=4800.ckpt
  # - version_path: data/logs/lightning_logs/version_215
  #   checkpoint: checkpoints/epoch=12-step=5200.ckpt

  # 20m dataset (ok results)
  # - version_path: data/logs/lightning_logs/version_225
  #   checkpoint: checkpoints/epoch=21-step=8800.ckpt

  ## With RX 7600 (8GB) and 32GB RAM

  # Trained on
  # # October 2025
  # 'T20KNA_20251003T174955'
  # 'T20KNB_20251003T174955'
  # # June 2025
  # 'T20KNA_20250620T173703'
  # 'T20KNB_20250620T173703'
  # # January 2025
  # 'T20KNA_20250116T211859'
  # 'T20KNB_20250116T211859'
  # 'T20KPC_20250116T211859'
  # # August 2022
  # 'T20KNA_20240714T072909'
  # 'T20KNB_20240714T072909'
  # 'T20KPC_20240714T072909'
  #
  # with 60m images at size of 192, a larger batch size of 16, 6 workers, and tested on
  # 'T20KQV_20251020T174731'
  # 'T20KQV_20250722T194121'
  # 'T20KQV_20250603T212126'
  #
  # good results for colmatados around Neuland
  # - version_path: data/logs/lightning_logs/version_24
  #   checkpoint: checkpoints/epoch=12-step=975.ckpt

  # full training set: bad results
  # - version_path: data/logs/lightning_logs/version_25
  #   checkpoint: checkpoints/epoch=6-step=525.ckpt

  # full minus 2022: good results for wetter areas around Neuland
  # - version_path: data/logs/lightning_logs/version_27
  #   checkpoint: checkpoints/epoch=11-step=900.ckpt

  # same, but batch size 12
  # for some reason, way better than 27
  # - version_path: data/logs/lightning_logs/version_33
  #   checkpoint: checkpoints/epoch=22-step=2300.ckpt

  # features 64-1024, batch size 12, 20m dataset
  # decent results, focuses too much on borders between fields, as opposed to 60m models
  - version_path: data/logs/lightning_logs/version_34
    checkpoint: checkpoints/epoch=28-step=2900.ckpt
