# For thesis FCN section
- model: fcn
  model_params:
    in_channels: 11
    classes: 1
    num_filters: 64
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: fcn
  model_params:
    in_channels: 11
    classes: 1
    num_filters: 96
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: fcn
  model_params:
    in_channels: 11
    classes: 1
    num_filters: 128
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: fcn
  model_params:
    in_channels: 11
    classes: 1
    num_filters: 256
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: fcn
  model_params:
    in_channels: 11
    classes: 1
    num_filters: 256
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50

# For thesis FarSeg section
- model: farseg
  model_params:
    backbone: resnet18
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B04
      - B03
      - B02
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: farseg
  model_params:
    backbone: resnet18
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B12
      - B8A
      - B04
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: farseg
  model_params:
    backbone: resnet50
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B04
      - B03
      - B02
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: farseg
  model_params:
    backbone: resnet50
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B12
      - B8A
      - B04
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: farseg
  model_params:
    backbone: resnet50
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B04
      - B03
      - B02
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: farseg
  model_params:
    backbone: resnet50
    backbone_pretrained: false
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
    bands:
      - B12
      - B8A
      - B04
  seed: 42
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50

# For thesis U-Net section
- model: unet
  model_params:
    features:
    - 64
    - 128
    - 256
    - 512
    in_channels: 11
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    batch_size: 3
    length: 1200
  seed: 42
  trainer_params:
    log_every_n_steps: 8
    max_epochs: 50
    min_epochs: 1
    patience: 7
    save_top_k: 1
- model: unet
  model_params:
    features:
    - 64
    - 128
    - 256
    - 512
    in_channels: 11
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    batch_size: 3
    length: 1200
  seed: 42
  trainer_params:
    log_every_n_steps: 8
    max_epochs: 50
    min_epochs: 1
    patience: 7
    save_top_k: 1
- model: unet
  model_params:
    features:
    - 32
    - 64
    - 128
    - 256
    - 512
    in_channels: 11
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    batch_size: 3
    length: 1200
  seed: 42
  trainer_params:
    log_every_n_steps: 8
    max_epochs: 50
    min_epochs: 1
    patience: 7
    save_top_k: 1
- model: unet
  model_params:
    features:
    - 32
    - 64
    - 128
    - 256
    - 512
    in_channels: 11
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    batch_size: 3
    length: 1200
  seed: 42
  trainer_params:
    log_every_n_steps: 8
    max_epochs: 50
    min_epochs: 1
    patience: 7
    save_top_k: 1
