- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 7
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 11
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 13
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 17
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
    weight_decay: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 1200
    batch_size: 3
  seed: 19
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
