- model: unet
  model_params:
    in_channels: 11
    features:
      - 32
      - 64
      - 128
      - 256
      - 512
    lr: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 800
    batch_size: 3
  seed: 3
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 1
- model: unet
  model_params:
    in_channels: 11
    features:
      - 64
      - 128
      - 256
      - 512
      - 1024
    lr: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 800
    batch_size: 3
  seed: 3
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 1
- model: unet
  model_params:
    in_channels: 11
    features:
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
    lr: 0.0001
  datamodule: sentinel2_60m
  datamodule_params:
    length: 800
    batch_size: 3
  seed: 3
  trainer_params:
    patience: 7
    save_top_k: 1
    max_epochs: 50
