# For thesis U-Net section
- model: unet
  model_params:
    features:
    - 64
    - 128
    - 256
    - 512
    in_channels: 11
    lr: 0.0001
    weight_decay: 0.001
  datamodule: sentinel2_60m
  datamodule_params:
    batch_size: 3
    length: 1200
    num_workers: 6
    patch_size: 192
  seed: 42
  trainer_params:
    log_every_n_steps: 8
    max_epochs: 50
    min_epochs: 1
    patience: 7
    save_top_k: 1
